spring:
  config:
    import: optional:file:.env[.properties]
  r2dbc:
    url: ${NAME_R2DBC_URL}
    username: ${NAME_R2DBC_USER}
    password: ${NAME_R2DBC_PASSWORD}
  flyway:
    url: ${NAME_DB_URL}
    user: ${NAME_DB_USER}
    password: ${NAME_DB_PASSWORD}
    locations: classpath:db/migration
  cloud:
    aws:
      credentials:
        access-key: ${NAME_AWS_ACCESS_KEY}
        secret-key: ${NAME_AWS_SECRET_KEY}
      region:
        static: ${NAME_AWS_REGION}

sqs:
  notifications:
    queue:
      name: ${NAME_SQS_QUEUE_NAME}
      region: ${NAME_SQS_QUEUE_NAME}
