spring:
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/
      username: postgres
        password: postgres
          flyway:
            url: jdbc:postgresql://localhost:5432/
              user: postgres
                password: postgres
                locations: classpath:db/migration
  cloud:
  aws:
    credentials:
      access-key:
        region:
          static: us-east-1


sqs:
  notifications:
    queue:
      name:
        rergion: us-east-1
